server:
  port: 8081

spring:
  application:
    name: cloud-payment-service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动包
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

eureka:
  client:
    #表示是否将自己注册进eureka服务，默认true
    register-with-eureka: true
    #是否从eureka抓取已有的注册信息，默认true。单节点无所谓，集群必须设置为true才能配合ribbon使用负债均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

  instance:
    instance-id: payment2
    prefer-ip-address: true


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lkf.springcloud.entity
