server:
  port: 80

spring:
  application:
    name: cloud-consumer-hystrix-order


eureka:
  client:
    #表示是否将自己注册进eureka服务，默认true
    register-with-eureka: true
    #是否从eureka抓取已有的注册信息，默认true。单节点无所谓，集群必须设置为true才能配合ribbon使用负债均衡
    fetch-registry: true
    service-url:
      #集群
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      #单机
      defaultZone: http://eureka7001.com:7001/eureka/


#ribbon的超时时间
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000


feign:
  hystrix:
    enabled: true